/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.lang.reflect.Array;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        int[] arr = {2,13,5,5,3,4};
        Mergesort(arr);
        System.out.println(Arrays.toString(arr));
    }

    public static void Mergesort(int[] arr){
        int n = arr.length;
        if (n>1){
            int mid = n/2;
            int[] left = Arrays.copyOfRange(arr, 0, mid);
            int[] right = Arrays.copyOfRange(arr, mid, n);

            Mergesort(left);
            Mergesort(right);
            Merge(left,right,arr);
        }
    }

    public static void Merge(int[] left, int[] right,int[] arr){
        int i = 0;
        int j = 0;
        int k = 0;

        while (i<left.length && j<right.length){
            if (left[i] <= right[j]){
                arr[k] = left[i];
                i++;
            }else {
                arr[k] = right[j];
                j++;
            }
            k++;}

        if (i == left.length){
            while (k< arr.length){
                arr[k] = right[j];
                j++;
                k++;
            }
        }else {
            while (k< arr.length){
                arr[k] = left[i];
                i++;
                k++;
            }
        }
    }
}
