/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package graphs;

public class App {



    public static void main(String[] args) {

        Graph<String> graph = new Graph();

        Vertex<String> vertex1 = graph.addNode("Mariam");
        Vertex<String> vertex2 = graph.addNode("Yousef");

        for (Vertex<String> vertex:
                graph.getNodes()) {
            System.out.println(vertex.getKey());
        }

        graph.addEdge(vertex1,vertex2,5);

        System.out.println(graph.toString());

    }

}
