/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtables;
import binaryTree.binaryTree.BinaryTree;
import trees.data.Node;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.*;

public class App {


    public static void main(String[] args) {
//        BinaryTree<Integer> binaryTree1 = new BinaryTree<>();
//        BinaryTree<Integer> binaryTree2 = new BinaryTree<>();
//        Hashtable<Integer,Integer> hashtable = new Hashtable<>();
//        binaryTree1.setRoot(new Node<Integer>(0));
//        binaryTree2.setRoot(new Node<Integer>(0));
//        binaryTree1.getRoot().setLeftChild(new Node<Integer>(1));
//        binaryTree1.getRoot().setRightChild(new Node<Integer>(2));
//        binaryTree2.getRoot().setRightChild(new Node<Integer>(2));
//        binaryTree2.getRoot().setLeftChild(new Node<Integer>(3));
//
//
//        System.out.println(hashtable.getIntersection(binaryTree1,binaryTree2));
//Hashtable<String, String> wordsHashtable = new Hashtable<>();
//        System.out.println(wordsHashtable.getRepeatedWord("Once upon a time, there was a brave princess who..."));
//        Hashtable<String,String> left = new Hashtable<>();
//        Hashtable<String,String> right = new Hashtable<>();
//
//        left.add("fond","enamored");
//        left.add("outfil","garb");
//
//        right.add("fond","averse");
//        right.add("guide","follow");
//
//        Hashtable<String, ArrayList<String>> newHash = left.leftJoin(left,right);

//        ArrayList<String> keys = newHash.leftJoin(left,right).getKeys();
//        System.out.println(newHash.getValues());
//        System.out.println(newHash.toString());
//        for (String key:
//                keys) {
//            System.out.println(newHash.findValue(key));
//            System.out.println(key);
//
//        }
//        String name= "My Name is Yousef";
//
//        Unique unique = new Unique();
//        System.out.println(unique.isUnique("Yousef nam"));
    }
}
