/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtables;
import java.util.regex.*;

public class App {


    public static void main(String[] args) {
        Hashtable<String, String> wordsHashtable = new Hashtable<>();

        System.out.println(wordsHashtable.getRepeatedWord("Once a, was a. brave princess who..."));

//        System.out.println();
    }
}
