/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static merge.sort.App.Mergesort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void mergeTest1(){
        int[] arr = {2,13,5,5,3,4};
        Mergesort(arr);
        assertEquals("[2, 3, 4, 5, 5, 13]",Arrays.toString(arr));
    }
    @Test void mergeTest2(){
        int[] arr = {20,18,12,8,5,-2};
        Mergesort(arr);
        assertEquals("[-2, 5, 8, 12, 18, 20]",Arrays.toString(arr));
    }
    @Test void mergeTest3(){
        int[] arr = {5,12,7,5,5,7};
        Mergesort(arr);
        assertEquals("[5, 5, 5, 7, 7, 12]",Arrays.toString(arr));
    }
    @Test void mergeTest4(){
        int[] arr = {2,3,5,7,13,11};
        Mergesort(arr);
        assertEquals("[2, 3, 5, 7, 11, 13]",Arrays.toString(arr));
    }
}
